import { EDITOR_PROCESS_MAP } from '../type';

// 有顺序优先级
export const COMMON_EDITORS_LINUX = {
  kiro: 'kiro',
  antigravity: 'antigravity',
  cursor: 'cursor',
  windsurf: 'windsurf',
  code: 'code',
  vscodium: 'vscodium',
  codium: 'codium',
  webstorm: 'webstorm',
  'webstorm.sh': 'webstorm',
  hbuilderx: 'hbuilderx',
  'hbuilderx.sh': 'hbuilderx',
  atom: 'atom',
  Brackets: 'brackets',
  'code-insiders': 'code-insiders',
  emacs: 'emacs',
  gvim: 'gvim',
  idea: 'idea',
  'idea.sh': 'idea',
  phpstorm: 'phpstorm',
  'phpstorm.sh': 'phpstorm',
  pycharm: 'pycharm',
  'pycharm.sh': 'pycharm',
  rubymine: 'rubymine',
  'rubymine.sh': 'rubymine',
  sublime_text: 'subl',
  nvim: 'nvim',
  vim: 'vim',
  goland: 'goland',
  'goland.sh': 'goland',
  rider: 'rider',
  'rider.sh': 'rider',
};

export const EDITOR_PROCESS_MAP_LINUX: EDITOR_PROCESS_MAP = {
  kiro: ['kiro'],
  antigravity: ['antigravity'],
  code: ['code'],
  'code-insiders': ['code-insiders'],
  webstorm: ['webstorm', 'webstorm.sh'],
  cursor: ['cursor'],
  windsurf: ['windsurf'],
  trae: ['trae'],
  comate: ['comate'],
  qoder: ['qoder'],
  codebuddy: ['codebuddy'],
  atom: ['atom'],
  hbuilder: ['hbuilderx', 'hbuilderx.sh'],
  phpstorm: ['phpstorm', 'phpstorm.sh'],
  pycharm: ['pycharm', 'pycharm.sh'],
  idea: ['idea', 'idea.sh'],
  codium: ['vscodium'],
  goland: ['goland'],
  brackets: ['Brackets'],
  rider: ['rider'],
  rubymine: ['rubymine', 'rubymine.sh'],
  sublime: ['sublime_text'],
  nvim: ['nvim'],
  vim: ['vim'],
  emacs: ['emacs'],
};
